### ISSUE TITLE
Bootloader Unlock Fails with "FastbootRemoteFailure" Error

### ISSUE THREAD

**Issue by Weingartens** [patrislav1/unisoc-unlock#10]
I am encountering an issue while trying to unlock the bootloader on my Unisoc device using `unisoc_unlock`. The process fails with the following error:

```
C:\Windows\System32>python -m unisoc_unlock unlock
Preparing to unlock the bootloader
OEM ID: (removed by me)
Download signature
Unlock bootloader, pls follow instructions on device screen
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\lib\site-packages\unisoc_unlock\__main__.py", line 3, in <module>
    main()
  File "C:\Python39\lib\site-packages\unisoc_unlock\cli.py", line 119, in main
    cmd()
  File "C:\Python39\lib\site-packages\unisoc_unlock\cli.py", line 74, in __call__
    self.dev._SimpleCommand(
  File "C:\Python39\lib\site-packages\unisoc_unlock\bundled_adb\fastboot.py", line 270, in _SimpleCommand
    return self._protocol.HandleSimpleResponses(**kwargs)
  File "C:\Python39\lib\site-packages\unisoc_unlock\bundled_adb\fastboot.py", line 104, in HandleSimpleResponses
    return self._AcceptResponses(b'OKAY', info_cb, timeout_ms=timeout_ms)
  File "C:\Python39\lib\site-packages\unisoc_unlock\bundled_adb\fastboot.py", line 172, in _AcceptResponses
    raise FastbootRemoteFailure('FAIL: %s', remaining)
unisoc_unlock.bundled_adb.fastboot.FastbootRemoteFailure: ("FAIL: b'Unlock bootloader fail.'", b'Unlock bootloader fail.')
```

I have tried the following steps:
1. Enabled OEM unlocking in the developer settings.
2. Ensured USB debugging is turned on.
3. The device is properly detected in `fastboot` mode (`fastboot devices` shows my device).
4. I followed the on-screen instructions to unlock the bootloader but received the above failure.

**Device Information**:
- Device: Oukitel C51
- OS: Android 14
- Python Version: 3.9
- Unisoc Unlock Version: 0.0.2
- Fastboot and ADB tools are up-to-date

Any guidance on how to resolve this issue would be greatly appreciated.

**Comment by patrislav1** [comment]
See [Disclaimer](https://github.com/patrislav1/unisoc-unlock?tab=readme-ov-file#disclaimer).
