### ISSUE TITLE
python3 -m unisoc_unlock command isn't working (on rg405m)

### ISSUE THREAD

**Issue by Wildtick** [patrislav1/unisoc-unlock#2]
Preparing to unlock the bootloader
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/wild/.local/lib/python3.11/site-packages/unisoc_unlock/__main__.py", line 3, in <module>
    main()
  File "/home/wild/.local/lib/python3.11/site-packages/unisoc_unlock/cli.py", line 119, in main
    cmd()
  File "/home/wild/.local/lib/python3.11/site-packages/unisoc_unlock/cli.py", line 71, in __call__
    self.prepare()
  File "/home/wild/.local/lib/python3.11/site-packages/unisoc_unlock/cli.py", line 40, in prepare
    self.dev.ConnectDevice()
  File "/home/wild/.local/lib/python3.11/site-packages/unisoc_unlock/bundled_adb/fastboot.py", line 255, in ConnectDevice
    self._handle = common.UsbHandle.FindAndOpen(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wild/.local/lib/python3.11/site-packages/unisoc_unlock/bundled_adb/common.py", line 221, in FindAndOpen
    dev.Open()
  File "/home/wild/.local/lib/python3.11/site-packages/unisoc_unlock/bundled_adb/common.py", line 117, in Open
    handle = self._device.open()
             ^^^^^^^^^^^^^^^^^^^
  File "/home/wild/.local/lib/python3.11/site-packages/usb1/__init__.py", line 2055, in open
    mayRaiseUSBError(libusb1.libusb_open(self.device_p, byref(handle)))
  File "/home/wild/.local/lib/python3.11/site-packages/usb1/__init__.py", line 127, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/home/wild/.local/lib/python3.11/site-packages/usb1/__init__.py", line 119, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorAccess: LIBUSB_ERROR_ACCESS [-3]
[wild@fedora ~]$ unisoc_unlock
Preparing to unlock the bootloader
Traceback (most recent call last):
  File "/home/wild/.local/bin/unisoc_unlock", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/wild/.local/lib/python3.11/site-packages/unisoc_unlock/cli.py", line 119, in main
    cmd()
  File "/home/wild/.local/lib/python3.11/site-packages/unisoc_unlock/cli.py", line 71, in __call__
    self.prepare()
  File "/home/wild/.local/lib/python3.11/site-packages/unisoc_unlock/cli.py", line 40, in prepare
    self.dev.ConnectDevice()
  File "/home/wild/.local/lib/python3.11/site-packages/unisoc_unlock/bundled_adb/fastboot.py", line 255, in ConnectDevice
    self._handle = common.UsbHandle.FindAndOpen(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wild/.local/lib/python3.11/site-packages/unisoc_unlock/bundled_adb/common.py", line 221, in FindAndOpen
    dev.Open()
  File "/home/wild/.local/lib/python3.11/site-packages/unisoc_unlock/bundled_adb/common.py", line 117, in Open
    handle = self._device.open()
             ^^^^^^^^^^^^^^^^^^^
  File "/home/wild/.local/lib/python3.11/site-packages/usb1/__init__.py", line 2055, in open
    mayRaiseUSBError(libusb1.libusb_open(self.device_p, byref(handle)))
  File "/home/wild/.local/lib/python3.11/site-packages/usb1/__init__.py", line 127, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/home/wild/.local/lib/python3.11/site-packages/usb1/__init__.py", line 119, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorAccess: LIBUSB_ERROR_ACCESS [-3]

**Comment by patrislav1** [comment]
`LIBUSB_ERROR_ACCESS` can be a permission issue. Maybe the udev rule for fastboot devices is not installed? (`/lib/udev/rules.d/51-android.rules`)

When you install the common adb tools (`sudo apt install android-sdk-platform-tools-common` on Ubuntu) it will install the udev rule and there should be no more permission issues.

**Comment by Wildtick** [comment]
i'm using fedora

**Comment by Wildtick** [comment]
ok just tried it and now it says 
 
No match for argument: android-sdk-platform-tools-common
Error: Unable to find a match: android-sdk-platform-tools-common

i'm i typing it in wrong or what?

**Comment by patrislav1** [comment]
I don't have a Fedora system so I can't give a step by step instruction here.

If your issue is caused by lack of access permissions, your choices are (in order of preference):
* Install udev rules to make the fastboot device user-accessible
* If you can't do that, find the fastboot device file with `lsusb` and `chmod a+rw` it to make it world accessible
* If that also fails, run unisoc-unlock as root.

**Comment by patrislav1** [comment]
I added the [permissions troubleshooting to the README](https://github.com/patrislav1/unisoc-unlock?tab=readme-ov-file#troubleshooting). Closing this issue due to inactivity. Feel free to reopen in case of new findings.
