### ISSUE TITLE
FAIL: b'Unlock bootloader fail.'", b'Unlock bootloader fail

### ISSUE THREAD

**Issue by hosamasd** [patrislav1/unisoc-unlock#4]
not work this problem happened how to solve pls?

Preparing to unlock the bootloader
OEM ID: 31303531313634333832303030363030
Download signature
Unlock bootloader, pls follow instructions on device screen
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/hosam/.local/lib/python3.11/site-packages/unisoc_unlock/__main__.py", line 3, in <module>
    main()
  File "/home/hosam/.local/lib/python3.11/site-packages/unisoc_unlock/cli.py", line 119, in main
    cmd()
  File "/home/hosam/.local/lib/python3.11/site-packages/unisoc_unlock/cli.py", line 74, in __call__
    self.dev._SimpleCommand(
  File "/home/hosam/.local/lib/python3.11/site-packages/unisoc_unlock/bundled_adb/fastboot.py", line 270, in _SimpleCommand
    return self._protocol.HandleSimpleResponses(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hosam/.local/lib/python3.11/site-packages/unisoc_unlock/bundled_adb/fastboot.py", line 104, in HandleSimpleResponses
    return self._AcceptResponses(b'OKAY', info_cb, timeout_ms=timeout_ms)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hosam/.local/lib/python3.11/site-packages/unisoc_unlock/bundled_adb/fastboot.py", line 172, in _AcceptResponses
    raise FastbootRemoteFailure('FAIL: %s', remaining)
unisoc_unlock.bundled_adb.fastboot.FastbootRemoteFailure: ("FAIL: b'Unlock bootloader fail.'", b'Unlock bootloader fail.')

itel s23 android 12

**Comment by patrislav1** [comment]
This unlock tool is for the Anbernic RG405M which needs a special unlock sequence, signing the device ID with a special key. Your phone doesn't seem to need this. See https://mobilewithdrivers.com/unlock-bootloader/itel-s23-plus-256gb-8gb-ram
