### ISSUE TITLE
FAIL: b"release user don\'t allow unlock!!!"'

### ISSUE THREAD

**Issue by AlterCreator** [patrislav1/unisoc-unlock#7]
Device RMX3261, Unisoc Tiger 610

LOG :
Preparing to unlock the bootloader
OEM ID: 30303231363644323137323430393338
Download signature
Unlock bootloader, pls follow instructions on device screen
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\bdstd\AppData\Local\Programs\Python\Python312\Lib\site-packages\unisoc_unlock\__main__.py", line 3, in <module>
    main()
  File "C:\Users\bdstd\AppData\Local\Programs\Python\Python312\Lib\site-packages\unisoc_unlock\cli.py", line 119, in main
    cmd()
  File "C:\Users\bdstd\AppData\Local\Programs\Python\Python312\Lib\site-packages\unisoc_unlock\cli.py", line 74, in __call__
    self.dev._SimpleCommand(
  File "C:\Users\bdstd\AppData\Local\Programs\Python\Python312\Lib\site-packages\unisoc_unlock\bundled_adb\fastboot.py", line 270, in _SimpleCommand
    return self._protocol.HandleSimpleResponses(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bdstd\AppData\Local\Programs\Python\Python312\Lib\site-packages\unisoc_unlock\bundled_adb\fastboot.py", line 104, in HandleSimpleResponses
    return self._AcceptResponses(b'OKAY', info_cb, timeout_ms=timeout_ms)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bdstd\AppData\Local\Programs\Python\Python312\Lib\site-packages\unisoc_unlock\bundled_adb\fastboot.py", line 172, in _AcceptResponses
    raise FastbootRemoteFailure('FAIL: %s', remaining)
unisoc_unlock.bundled_adb.fastboot.FastbootRemoteFailure: ('FAIL: b"release user don\'t allow unlock!!!"', b"release user don't allow unlock!!!")

Did this mean the manufacture use is own private key? not default one?

**Comment by AlterCreator** [comment]
fastboot flashing lock
result 👍 
OKAY [  0.009s]
Finished. Total time: 0.010s

fastboot flashing unlock
FAILED (remote: 'unknown cmd.')
fastboot: error: Command failed

**Comment by hadtosignup** [comment]
^^ Basically, I got the same output but for different device - ZTE Nubia Neo 5G (model: 8150N; CPU: Unisoc T820)
except being on Linux machine where $PATH differ. 

The results are same for both _user_ (in wheel group) and _root_.
This one's for root:

python3 -m unisoc_unlock unlock
Preparing to unlock the bootloader
OEM ID: 333230333434373638353737
Download signature
Unlock bootloader, pls follow instructions on device screen
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/python3.9/site-packages/unisoc_unlock/__main__.py", line 3, in <module>
    main()
  File "/usr/lib64/python3.9/site-packages/unisoc_unlock/cli.py", line 119, in main
    cmd()
  File "/usr/lib64/python3.9/site-packages/unisoc_unlock/cli.py", line 74, in __call__
    self.dev._SimpleCommand(
  File "/usr/lib64/python3.9/site-packages/unisoc_unlock/bundled_adb/fastboot.py", line 270, in _SimpleCommand
    return self._protocol.HandleSimpleResponses(**kwargs)
  File "/usr/lib64/python3.9/site-packages/unisoc_unlock/bundled_adb/fastboot.py", line 104, in HandleSimpleResponses
    return self._AcceptResponses(b'OKAY', info_cb, timeout_ms=timeout_ms)
  File "/usr/lib64/python3.9/site-packages/unisoc_unlock/bundled_adb/fastboot.py", line 172, in _AcceptResponses
    raise FastbootRemoteFailure('FAIL: %s', remaining)
unisoc_unlock.bundled_adb.fastboot.FastbootRemoteFailure: ("FAIL: b'Unlock bootloader fail.'", b'Unlock bootloader fail.')

FWIW the output of the `fastboot devices` command is:
32xxxx77	 fastboot Data  _<<< Never seen this Data output_

 and there is NO fastboot screen, just the same (this time static) boot logo.

Sorry if this looks like issue jacking. @AlterCreator 
Feel free to move it to separate thread if needed. @patrislav1 
Cheers!

**Comment by patrislav1** [comment]
See [Disclaimer](https://github.com/patrislav1/unisoc-unlock?tab=readme-ov-file#disclaimer).
